services:
  db:
    image: mongo:latest
    container_name: weather_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  grpc_server:
    build: .
    container_name: weather_grpc
    command: ["python", "-m", "app.grpc_main"]
    ports:
      - "50051:50051"
    depends_on:
      - db
    volumes:
      - ./data/logs:/app/data/logs
    env_file:
      - .env
    restart: unless-stopped

  fastapi_server:
    build: .
    container_name: weather_fastapi
    command: ["uvicorn", "app.fastapi_main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - grpc_server
    volumes:
      - ./data/logs:/app/data/logs
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo_data:
